---
apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    project: jenkins-kubernetes-cicd
spec:
  selector:
    project: jenkins-kubernetes-cicd
  ports:
    - name: service-port
      protocol: TCP
      port: 80
      targetPort: container-port
