---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    project: jenkins-kubernetes-cicd
spec:
  selector:
    project: jenkins-kubernetes-cicd
  ports:
    - name: app-service-port_http
      protocol: TCP
      port: 80
      targetPort: app-container-port
