---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    project: jenkins-kubernetes-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      project: jenkins-kubernetes-cicd
  template:
    metadata:
      labels:
        project: jenkins-kubernetes-cicd
    spec:
      containers:
        - name: container
          image: danielgiustiniperez/jenkins-kubernetes-cicd:latest
          ports:
            - name: container-port
              containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: '3000'
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: password
