---
apiVersion: apps/v1
kind: Deployment
meta:
  name: app-deployment
  labels:
    project: jenkins-kubernetes-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      project: jenkins-kubernetes-cicd
  template:
    metadata:
      labels:
        project: jenkins-kubernetes-cicd
    spec:
      containers:
        - name: app-container
          image: danielgiustiniperez/jenkins-kubernetes-cicd:latest
          ports:
            - name: app-container-port
              containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: 3000
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: app-username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: app-password
